//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animals()
        {
            this.Client_animals = new HashSet<Client_animals>();
        }
    
        public int Iid_animals { get; set; }
        public string Nickname { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public int Age { get; set; }
        public string View { get; set; }
        public string Floor { get; set; }
        public int Id_breed { get; set; }
    
        public virtual Breed Breed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_animals> Client_animals { get; set; }
    }
}
