//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_animals
    {
        public int id_Client_animals { get; set; }
        public int id_client { get; set; }
        public int id_animals { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Client Client { get; set; }
    }
}
