//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int Iid_reception { get; set; }
        public int Id_entry { get; set; }
        public string Diagnosis { get; set; }
        public string Recommendations { get; set; }
        public string Duration_of_treatment { get; set; }
        public string Prescription_of_medicines { get; set; }
    
        public virtual Entry Entry { get; set; }
    }
}
